apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arc-base-image-chart.fullname" . }}-agents
  labels:
    {{- include "arc-base-image-chart.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.arc.agents }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
