{{- if .Values.arc.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arc-base-image-chart.fullname" . }}-config
  labels:
    {{- include "arc-base-image-chart.labels" . | nindent 4 }}
data:
  application.yml: |-
    {{- .Values.arc.config.content | nindent 4 }}
{{- end }}