apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arc-base-image-chart.fullname" . }}
  labels:
    {{- include "arc-base-image-chart.labels" . | nindent 4 }}
data:
  application.yml: |-
    {{- .Values.arc.config | nindent 4 }}
