{{- if .Values.permitK8sAccess }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "arc-base-image-chart.fullname" . }}-helm-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "arc-base-image-chart.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "arc-base-image-chart.fullname" . }}-helm-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
